language: node_js
cache: npm
stages:
  - check
  - test
  - cov

node_js:
  - 'lts/*'
  - '14'

os:
  - linux
  - osx

script: npx nyc -s npm run test:node -- --bail
after_success: npx nyc report --reporter=text-lcov > coverage.lcov && npx codecov

jobs:
  include:
    - stage: check
      script:
        - npx aegir build --bundlesize
        # Remove pull libs once ping is async
        - npx aegir dep-check -- -i pull-handshake -i pull-stream
        - npm run lint

    - stage: test
      name: chrome
      addons:
        chrome: stable
      script:
        - npx aegir test -t browser -t webworker

    - stage: test
      name: firefox
      addons:
        firefox: latest
      script:
        - npx aegir test -t browser -t webworker -- --browsers FirefoxHeadless

    - stage: test
      name: interop
      script:
        - cd node_modules/interop-libp2p
        - npm install
        - LIBP2P_JS=${TRAVIS_BUILD_DIR}/src/index.js npx aegir test -t node --bail

    - stage: test
      name: example - auto-relay
      script:
        - cd examples
        - npm install
        - npm run test -- auto-relay

notifications:
  email: false