name: Examples
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - uses: ipfs/aegir/actions/cache-node-modules@master

  test-examples:
    name: Test example ${{ matrix.example.name }}
    runs-on: ubuntu-latest
    needs: build
    continue-on-error: true
    strategy:
      matrix:
        example:
          - name: js-libp2p-example-chat
            repo: https://github.com/libp2p/js-libp2p-example-chat.git
            deps:
              - '@libp2p/peer-id-factory@$PWD/packages/peer-id-factory'
              - '@libp2p/tcp@$PWD/packages/transport-tcp'
              - '@libp2p/websockets@$PWD/packages/transport-websockets'
              - 'libp2p@$PWD/packages/libp2p'
          - name: js-libp2p-example-circuit-relay
            repo: https://github.com/libp2p/js-libp2p-example-circuit-relay.git
            deps:
              - '@libp2p/circuit-relay-v2@$PWD/packages/transport-circuit-relay-v2'
              - '@libp2p/identify@$PWD/packages/protocol-identify'
              - '@libp2p/websockets@$PWD/packages/transport-websockets'
              - 'libp2p@$PWD/packages/libp2p'
          - name: js-libp2p-example-connection-encryption
            repo: https://github.com/libp2p/js-libp2p-example-connection-encryption.git
            deps:
              - '@libp2p/plaintext@$PWD/packages/connection-encrypter-plaintext'
              - '@libp2p/tcp@$PWD/packages/transport-tcp'
              - 'libp2p@$PWD/packages/libp2p'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - uses: ipfs/aegir/actions/cache-node-modules@master
      - run: npx xvfb-maybe aegir test-dependant ${{ matrix.example.repo }} --deps ${{ join(matrix.example.deps, ',') }}
