name: examples
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16
    - uses: actions/cache@v2
      id: cache
      env:
        CACHE_NAME: cache-node-modules
      with:
        path: |
          ~/.cache
          ~/.npm
          ./node_modules
          ./dist
          ./examples/node_modules
        key: ${{ runner.os }}-build-${{ env.CACHE_NAME }}-${{ github.event.pull_request.head.sha }}
    - name: Install Dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        npm install
        npm run build
        cd examples && npm i
    - run: npx aegir lint
    - run: npx aegir ts -p check
  test-auto-relay-example:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - uses: actions/cache@v2
        id: cache
        env:
          CACHE_NAME: cache-node-modules
        with:
          path: |
            ~/.cache
            ~/.npm
            ./node_modules
            ./dist
            ./examples/node_modules
          key: ${{ runner.os }}-build-${{ env.CACHE_NAME }}-${{ github.event.pull_request.head.sha }}
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          npm install
          npm run build
          cd examples && npm i
      - run: cd examples && npm run test -- auto-relay
  test-chat-example:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - uses: actions/cache@v2
        id: cache
        env:
          CACHE_NAME: cache-node-modules
        with:
          path: |
            ~/.cache
            ~/.npm
            ./node_modules
            ./dist
            ./examples/node_modules
          key: ${{ runner.os }}-build-${{ env.CACHE_NAME }}-${{ github.event.pull_request.head.sha }}
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          npm install
          npm run build
          cd examples && npm i
      - run: cd examples && npm run test -- chat
  test-connection-encryption-example:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - uses: actions/cache@v2
        id: cache
        env:
          CACHE_NAME: cache-node-modules
        with:
          path: |
            ~/.cache
            ~/.npm
            ./node_modules
            ./dist
            ./examples/node_modules
          key: ${{ runner.os }}-build-${{ env.CACHE_NAME }}-${{ github.event.pull_request.head.sha }}
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          npm install
          npm run build
          cd examples && npm i
      - run: cd examples && npm run test -- connection-encryption
  test-discovery-mechanisms-example:
    needs: check
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - uses: actions/cache@v2
        id: cache
        env:
          CACHE_NAME: cache-node-modules
        with:
          path: |
            ~/.cache
            ~/.npm
            ./node_modules
            ./dist
            ./examples/node_modules
          key: ${{ runner.os }}-build-${{ env.CACHE_NAME }}-${{ github.event.pull_request.head.sha }}
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          npm install
          npm run build
          cd examples && npm i
      - run: cd examples && npm run test -- discovery-mechanisms
  test-echo-example:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - uses: actions/cache@v2
        id: cache
        env:
          CACHE_NAME: cache-node-modules
        with:
          path: |
            ~/.cache
            ~/.npm
            ./node_modules
            ./dist
            ./examples/node_modules
          key: ${{ runner.os }}-build-${{ env.CACHE_NAME }}-${{ github.event.pull_request.head.sha }}
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          npm install
          npm run build
          cd examples && npm i
      - run: cd examples && npm run test -- echo
  test-libp2p-in-the-browser-example:
    needs: check
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - uses: actions/cache@v2
        id: cache
        env:
          CACHE_NAME: cache-node-modules
        with:
          path: |
            ~/.cache
            ~/.npm
            ./node_modules
            ./dist
            ./examples/node_modules
          key: ${{ runner.os }}-build-${{ env.CACHE_NAME }}-${{ github.event.pull_request.head.sha }}
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          npm install
          npm run build
          cd examples && npm i
      - run: cd examples && npm run test -- libp2p-in-the-browser
  test-peer-and-content-routing-example:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
            node-version: 16
      - uses: actions/cache@v2
        id: cache
        env:
          CACHE_NAME: cache-node-modules
        with:
          path: |
            ~/.cache
            ~/.npm
            ./node_modules
            ./dist
            ./examples/node_modules
          key: ${{ runner.os }}-build-${{ env.CACHE_NAME }}-${{ github.event.pull_request.head.sha }}
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          npm install
          npm run build
          cd examples && npm i
      - run: cd examples && npm run test -- peer-and-content-routing
  test-pnet-example:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
            node-version: 16
      - uses: actions/cache@v2
        id: cache
        env:
          CACHE_NAME: cache-node-modules
        with:
          path: |
            ~/.cache
            ~/.npm
            ./node_modules
            ./dist
            ./examples/node_modules
          key: ${{ runner.os }}-build-${{ env.CACHE_NAME }}-${{ github.event.pull_request.head.sha }}
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          npm install
          npm run build
          cd examples && npm i
      - run: cd examples && npm run test -- pnet
  test-protocol-and-stream-muxing-example:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
            node-version: 16
      - uses: actions/cache@v2
        id: cache
        env:
          CACHE_NAME: cache-node-modules
        with:
          path: |
            ~/.cache
            ~/.npm
            ./node_modules
            ./dist
            ./examples/node_modules
          key: ${{ runner.os }}-build-${{ env.CACHE_NAME }}-${{ github.event.pull_request.head.sha }}
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          npm install
          npm run build
          cd examples && npm i
      - run: cd examples && npm run test -- protocol-and-stream-muxing
  test-pubsub-example:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
            node-version: 16
      - uses: actions/cache@v2
        id: cache
        env:
          CACHE_NAME: cache-node-modules
        with:
          path: |
            ~/.cache
            ~/.npm
            ./node_modules
            ./dist
            ./examples/node_modules
          key: ${{ runner.os }}-build-${{ env.CACHE_NAME }}-${{ github.event.pull_request.head.sha }}
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          npm install
          npm run build
          cd examples && npm i
      - run: cd examples && npm run test -- pubsub
  test-transports-example:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
            node-version: 16
      - uses: actions/cache@v2
        id: cache
        env:
          CACHE_NAME: cache-node-modules
        with:
          path: |
            ~/.cache
            ~/.npm
            ./node_modules
            ./dist
            ./examples/node_modules
          key: ${{ runner.os }}-build-${{ env.CACHE_NAME }}-${{ github.event.pull_request.head.sha }}
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          npm install
          npm run build
          cd examples && npm i
      - run: cd examples && npm run test -- transports
  test-webrtc-direct-example:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
            node-version: 16
      - uses: actions/cache@v2
        id: cache
        env:
          CACHE_NAME: cache-node-modules
        with:
          path: |
            ~/.cache
            ~/.npm
            ./node_modules
            ./dist
            ./examples/node_modules
          key: ${{ runner.os }}-build-${{ env.CACHE_NAME }}-${{ github.event.pull_request.head.sha }}
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          npm install
          npm run build
          cd examples && npm i
      - run: cd examples && npm run test -- webrtc-direct
